"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List, Any  # Self is not supported by pydantic
from pydantic.types import Json
from utils.enums import *


class equipment_list_item(BaseModel):
     id: Optional[int]
     equipment_list_id: int
     row_id: int
     field: Optional[str]
     value: Optional[str]
     modified_on: Optional[datetime]
     class Config:
        from_attributes = True


class equipment_list_itemCreate(BaseModel):
    equipment_list_id: int
    row_id: int
    field: Optional[str]
    value: Optional[str]
    class Config:
        from_attributes = True

class equipment_list_itemUpdate(BaseModel):
    value: Optional[str]
    class Config:
        from_attributes = True


class equipment_list_itemUpsert(BaseModel):
    id: Optional[int]
    equipment_list_id: int
    row_id: int
    field: Optional[str]
    value: Optional[str]
    class Config:
        from_attributes = True