"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List, Any  # Self is not supported by pydantic
from pydantic.types import Json
from utils.enums import *


class equipment_list(BaseModel):
     id: Optional[int]
     project_id: int
     file_name: str
     type: str
     s3_key: Optional[str]
     modified_on: Optional[datetime]
     class Config:
        from_attributes = True


class equipment_listCreate(BaseModel):
    project_id: int
    file_name: str
    type: str
    s3_key: Optional[str]
    class Config:
        from_attributes = True

class equipment_listUpdate(BaseModel):
    project_id: int
    file_name: str
    type: str
    s3_key: Optional[str]
    class Config:
        from_attributes = True


class equipment_listUpsert(BaseModel):
    id: Optional[int]
    project_id: int
    file_name: str
    type: str
    s3_key: Optional[str]
    class Config:
        from_attributes = True