"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List, Any  # Self is not supported by pydantic
from pydantic.types import Json
from utils.enums import *


class job(BaseModel):
     id: Optional[int]
     name: str
     type: str
     status: str
     project_id: int
     file_id: Optional[int]
     created_at: Optional[datetime]
     completed_at: Optional[datetime]
     error_message: Optional[str]
     modified_on: Optional[datetime]
     class Config:
        from_attributes = True


class jobCreate(BaseModel):
    name: str
    type: str
    status: str
    project_id: int
    file_id: Optional[int]
    created_at: Optional[datetime]
    completed_at: Optional[datetime]
    error_message: Optional[str]
    class Config:
        from_attributes = True

class jobUpdate(BaseModel):
    name: str
    type: str
    status: str
    project_id: int
    file_id: Optional[int]
    created_at: Optional[datetime]
    completed_at: Optional[datetime]
    error_message: Optional[str]
    class Config:
        from_attributes = True


class jobUpsert(BaseModel):
    id: Optional[int]
    name: str
    type: str
    status: str
    project_id: int
    file_id: Optional[int]
    created_at: Optional[datetime]
    completed_at: Optional[datetime]
    error_message: Optional[str]
    class Config:
        from_attributes = True