"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List, Any  # Self is not supported by pydantic
from pydantic.types import Json
from utils.enums import *


class pid_file(BaseModel):
     id: Optional[int]
     project_id: int
     version: Optional[str]
     file_name: Optional[str]
     file_uuid: Optional[str]
     technical_name: Optional[str]
     s3_key: Optional[str]
     modified_on: Optional[datetime]
     class Config:
        from_attributes = True


class pid_fileCreate(BaseModel):
    project_id: int
    version: Optional[str]
    file_name: Optional[str]
    file_uuid: Optional[str]
    technical_name: Optional[str]
    s3_key: Optional[str]
    class Config:
        from_attributes = True

class pid_fileUpdate(BaseModel):
    project_id: int
    version: Optional[str]
    file_name: Optional[str]
    technical_name: Optional[str]
    s3_key: Optional[str]
    class Config:
        from_attributes = True


class pid_fileUpsert(BaseModel):
    id: Optional[int]
    project_id: int
    version: Optional[str]
    file_name: Optional[str]
    file_uuid: Optional[str]
    technical_name: Optional[str]
    s3_key: Optional[str]
    class Config:
        from_attributes = True