"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List, Any  # Self is not supported by pydantic
from pydantic.types import Json
from utils.enums import *


class pid_file_page(BaseModel):
     id: Optional[int]
     pid_file_id: int
     page_number: int
     height: Optional[int]
     width: Optional[int]
     rotation: Optional[int]
     image_s3_key: Optional[str]
     modified_on: Optional[datetime]
     class Config:
        from_attributes = True


class pid_file_pageCreate(BaseModel):
    pid_file_id: int
    page_number: int
    height: Optional[int]
    width: Optional[int]
    rotation: Optional[int]
    image_s3_key: Optional[str]
    class Config:
        from_attributes = True

class pid_file_pageUpdate(BaseModel):
    height: Optional[int]
    width: Optional[int]
    rotation: Optional[int]
    image_s3_key: Optional[str]
    class Config:
        from_attributes = True


class pid_file_pageUpsert(BaseModel):
    id: Optional[int]
    pid_file_id: int
    page_number: int
    height: Optional[int]
    width: Optional[int]
    rotation: Optional[int]
    image_s3_key: Optional[str]
    class Config:
        from_attributes = True