"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List, Any  # Self is not supported by pydantic
from pydantic.types import Json
from utils.enums import *


class pid_file_link(BaseModel):
     id: Optional[int]
     pid_file_page_id: int
     pid_file_id: int
     linked_pid_file_id: Optional[int]
     type: str
     name: str
     x0: int
     y0: int
     x1: int
     y1: int
     image_s3_key: Optional[str]
     modified_on: Optional[datetime]
     class Config:
        from_attributes = True


class pid_file_linkCreate(BaseModel):
    pid_file_page_id: int
    pid_file_id: int
    linked_pid_file_id: Optional[int]
    type: str
    name: str
    x0: int
    y0: int
    x1: int
    y1: int
    image_s3_key: Optional[str]
    class Config:
        from_attributes = True

class pid_file_linkUpdate(BaseModel):
    linked_pid_file_id: Optional[int]
    x0: int
    y0: int
    x1: int
    y1: int
    image_s3_key: Optional[str]
    class Config:
        from_attributes = True


class pid_file_linkUpsert(BaseModel):
    id: Optional[int]
    pid_file_page_id: int
    pid_file_id: int
    linked_pid_file_id: Optional[int]
    type: str
    name: str
    x0: int
    y0: int
    x1: int
    y1: int
    image_s3_key: Optional[str]
    class Config:
        from_attributes = True