"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List, Any  # Self is not supported by pydantic
from pydantic.types import Json
from utils.enums import *


class pid_tag(BaseModel):
     id: Optional[int]
     pid_file_page_id: int
     name: str
     tag_value: str
     type: str
     sub_type: str
     x0: int
     y0: int
     x1: int
     y1: int
     confidence: float
     candidates: Optional[dict]
     modified_on: Optional[datetime]
     class Config:
        from_attributes = True


class pid_tagCreate(BaseModel):
    pid_file_page_id: int
    name: str
    tag_value: str
    type: str
    sub_type: str
    x0: int
    y0: int
    x1: int
    y1: int
    confidence: float
    candidates: Optional[dict]
    class Config:
        from_attributes = True

class pid_tagUpdate(BaseModel):
    tag_value: str
    sub_type: str
    x0: int
    y0: int
    x1: int
    y1: int
    confidence: float
    candidates: Optional[dict]
    class Config:
        from_attributes = True


class pid_tagUpsert(BaseModel):
    id: Optional[int]
    pid_file_page_id: int
    name: str
    tag_value: str
    type: str
    sub_type: str
    x0: int
    y0: int
    x1: int
    y1: int
    confidence: float
    candidates: Optional[dict]
    class Config:
        from_attributes = True