"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List, Any  # Self is not supported by pydantic
from pydantic.types import Json
from utils.enums import *


class project(BaseModel):
     id: Optional[int]
     name: str
     owner: str
     modified_on: Optional[datetime]
     class Config:
        from_attributes = True


class projectCreate(BaseModel):
    name: str
    owner: str
    class Config:
        from_attributes = True

class projectUpdate(BaseModel):
    name: str
    owner: str
    class Config:
        from_attributes = True


class projectUpsert(BaseModel):
    id: Optional[int]
    name: str
    owner: str
    class Config:
        from_attributes = True