"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""
from typing import TypeVar, Optional, Sequence, Dict

from fastapi import HTTPException, Depends
from pydantic import BaseModel


T = TypeVar("T", bound=BaseModel)
PAGINATION = Dict[str, Optional[int]]
DEPENDENCIES = Optional[Sequence[Depends]]
NOT_FOUND = HTTPException(404, "Item not found")
NOT_AUTHORIZED = HTTPException(403, "Not Authorized")
PYDANTIC_SCHEMA = BaseModel
