"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""
import os
import boto3
import json



def get_ssm_parameter(path: str, with_decryption: bool = False) -> str:
    ssm_client = boto3.client(
        "ssm",
        # region_name="eu-west-1",
        use_ssl=True
    )

    params = {"Name": path}
    if with_decryption:
        params["WithDecryption"] = True

    parameter = ssm_client.get_parameter(
        **params
    )["Parameter"]["Value"]

    return parameter

class Settings:
    client = boto3.client("secretsmanager")
    secret_arn = os.environ.get("DB_SECRET_ARN","arn:aws:secretsmanager:eu-west-1:643553455790:secret:PIDDBConstructPostgresInsta-0xhzYgm9Otmr-4s2xrh")
    secret_value = client.get_secret_value(SecretId=secret_arn)

    credentials = json.loads(secret_value["SecretString"])
    print(credentials)
    POSTGRES_USER = credentials["username"]
    POSTGRES_PASSWORD = credentials["password"]
    POSTGRES_SERVER = credentials["host"]
    POSTGRES_PORT: int = int(credentials.get("port", 5432))

    PID_PROCESSING_QUEUE_URL = os.environ.get("PID_PROCESSING_QUEUE_URL")

    API_URL = get_ssm_parameter(f"/micro-services/api/url")
    API_USERNAME =""
    API_PASSWORD = ""

    POSTGRES_DB: str = os.getenv("POSTGRES_DB", "pid")
    DATABASE_URL: str = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_SERVER}:{POSTGRES_PORT}/{POSTGRES_DB}"

settings = Settings()
