"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from fastapi import APIRouter
from endpoints.Router_job import model_router as job_Router
from endpoints.Router_pid_file import model_router as pid_file_Router
from endpoints.Router_pid_file_link import model_router as pid_file_link_Router
from endpoints.Router_pid_file_page import model_router as pid_file_page_Router
from endpoints.Router_pid_tag import model_router as pid_tag_Router
from endpoints.Router_project import model_router as project_Router
from endpoints.Router_equipment_list import model_router as equipment_list_Router
from endpoints.Router_equipment_list_item import model_router as equipment_list_item_Router

api_router = APIRouter()
api_router.include_router(job_Router)
api_router.include_router(pid_file_Router)
api_router.include_router(pid_file_link_Router)
api_router.include_router(pid_file_page_Router)
api_router.include_router(pid_tag_Router)
api_router.include_router(project_Router)
api_router.include_router(equipment_list_Router)
api_router.include_router(equipment_list_item_Router)
