"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from typing import Optional
from utils.enums import *
from core.api.sento_router import SentoRouter
from core.database.db import get_db
from schemas.project import project as Schemaproject
from schemas.project import projectCreate as SchemaprojectCreate
from schemas.project import projectUpdate as SchemaprojectUpdate
from schemas.project import projectUpsert as SchemaprojectUpsert

from datetime import datetime

from models.project import project as Modelproject

def get_all_filter_function(): return {}


get_all_filter_meta = {}


model_router = SentoRouter(
                    schema=Schemaproject,
                    db = get_db,
                    prefix="project",
                    db_model=Modelproject,
                    create_schema = SchemaprojectCreate,
                    update_schema = SchemaprojectUpdate,
                    upsert_schema = SchemaprojectUpsert,
                    get_all_filter_function= get_all_filter_function,
                    get_all_filter_meta = get_all_filter_meta,
                    create_one_callback=False,
                    update_one_callback=False,
                    delete_one_callback=False,
                    delete_all_callback=False,
                    unique_fields=[]
                )