"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from typing import Optional
from utils.enums import *
from core.api.sento_router import SentoRouter
from core.database.db import get_db
from schemas.pid_tag import pid_tag as Schemapid_tag
from schemas.pid_tag import pid_tagCreate as Schemapid_tagCreate
from schemas.pid_tag import pid_tagUpdate as Schemapid_tagUpdate
from schemas.pid_tag import pid_tagUpsert as Schemapid_tagUpsert

from datetime import datetime

from models.pid_tag import pid_tag as Modelpid_tag

def get_all_filter_function(pid_file_page_id:int=None,name:str=None):
	return {"pid_file_page_id":pid_file_page_id,"name":name}


get_all_filter_meta = {'pid_file_page_id': {'condition': '==', 'column': 'pid_file_page_id'}, 'name': {'condition': '==', 'column': 'name'}, 'type': {'condition': '==', 'column': 'type'}}


model_router = SentoRouter(
                    schema=Schemapid_tag,
                    db = get_db,
                    prefix="pid_tag",
                    db_model=Modelpid_tag,
                    create_schema = Schemapid_tagCreate,
                    update_schema = Schemapid_tagUpdate,
                    upsert_schema = Schemapid_tagUpsert,
                    get_all_filter_function= get_all_filter_function,
                    get_all_filter_meta = get_all_filter_meta,
                    create_one_callback=False,
                    update_one_callback=False,
                    delete_one_callback=False,
                    delete_all_callback=False,
                    unique_fields=['pid_file_page_id', 'name']
                )