"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from typing import Optional
from utils.enums import *
from core.api.sento_router import SentoRouter
from core.database.db import get_db
from schemas.pid_file_page import pid_file_page as Schemapid_file_page
from schemas.pid_file_page import pid_file_pageCreate as Schemapid_file_pageCreate
from schemas.pid_file_page import pid_file_pageUpdate as Schemapid_file_pageUpdate
from schemas.pid_file_page import pid_file_pageUpsert as Schemapid_file_pageUpsert

from datetime import datetime

from models.pid_file_page import pid_file_page as Modelpid_file_page

def get_all_filter_function(pid_file_id:int=None,page_number:int=None):
	return {"pid_file_id":pid_file_id,"page_number":page_number}


get_all_filter_meta = {'pid_file_id': {'condition': '==', 'column': 'pid_file_id'}, 'page_number': {'condition': '==', 'column': 'page_number'}}


model_router = SentoRouter(
                    schema=Schemapid_file_page,
                    db = get_db,
                    prefix="pid_file_page",
                    db_model=Modelpid_file_page,
                    create_schema = Schemapid_file_pageCreate,
                    update_schema = Schemapid_file_pageUpdate,
                    upsert_schema = Schemapid_file_pageUpsert,
                    get_all_filter_function= get_all_filter_function,
                    get_all_filter_meta = get_all_filter_meta,
                    create_one_callback=False,
                    update_one_callback=False,
                    delete_one_callback=False,
                    delete_all_callback=False,
                    unique_fields=['pid_file_id', 'page_number']
                )