"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from typing import Optional
from utils.enums import *
from core.api.sento_router import SentoRouter
from core.database.db import get_db
from schemas.job import job as Schemajob
from schemas.job import jobCreate as SchemajobCreate
from schemas.job import jobUpdate as SchemajobUpdate
from schemas.job import jobUpsert as SchemajobUpsert

from datetime import datetime

from models.job import job as Modeljob

def get_all_filter_function(project_id:Optional[int]=None):
	return {"project_id":project_id}


get_all_filter_meta = {'project_id': {'condition': '==', 'column': 'project_id'}}


model_router = SentoRouter(
                    schema=Schemajob,
                    db = get_db,
                    prefix="job",
                    db_model=Modeljob,
                    create_schema = SchemajobCreate,
                    update_schema = SchemajobUpdate,
                    upsert_schema = SchemajobUpsert,
                    get_all_filter_function= get_all_filter_function,
                    get_all_filter_meta = get_all_filter_meta,
                    create_one_callback=False,
                    update_one_callback=False,
                    delete_one_callback=False,
                    delete_all_callback=False,
                    unique_fields=[]
                )