"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from typing import Optional
from utils.enums import *
from core.api.sento_router import SentoRouter
from core.database.db import get_db
from schemas.equipment_list import equipment_list as Schemaequipment_list
from schemas.equipment_list import equipment_listCreate as Schemaequipment_listCreate
from schemas.equipment_list import equipment_listUpdate as Schemaequipment_listUpdate
from schemas.equipment_list import equipment_listUpsert as Schemaequipment_listUpsert

from datetime import datetime

from models.equipment_list import equipment_list as Modelequipment_list

def get_all_filter_function(project_id:Optional[int]=None):
	return {"project_id":project_id}


get_all_filter_meta = {'project_id': {'condition': '==', 'column': 'project_id'}}


model_router = SentoRouter(
                    schema=Schemaequipment_list,
                    db = get_db,
                    prefix="equipment",
                    db_model=Modelequipment_list,
                    create_schema = Schemaequipment_listCreate,
                    update_schema = Schemaequipment_listUpdate,
                    upsert_schema = Schemaequipment_listUpsert,
                    get_all_filter_function= get_all_filter_function,
                    get_all_filter_meta = get_all_filter_meta,
                    create_one_callback=False,
                    update_one_callback=False,
                    delete_one_callback=False,
                    delete_all_callback=False,
                    unique_fields=[]
                )