"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from typing import Optional
from utils.enums import *
from core.api.sento_router import SentoRouter
from core.database.db import get_db
from schemas.equipment_list_item import equipment_list_item as Schemaequipment_list_item
from schemas.equipment_list_item import equipment_list_itemCreate as Schemaequipment_list_itemCreate
from schemas.equipment_list_item import equipment_list_itemUpdate as Schemaequipment_list_itemUpdate
from schemas.equipment_list_item import equipment_list_itemUpsert as Schemaequipment_list_itemUpsert

from datetime import datetime

from models.equipment_list_item import equipment_list_item as Modelequipment_list_item

def get_all_filter_function(equipment_list_id:int=None,row_id:int=None,field:Optional[str]=None):
	return {"equipment_list_id":equipment_list_id,"row_id":row_id,"field":field}


get_all_filter_meta = {'equipment_list_id': {'condition': '==', 'column': 'equipment_list_id'}, 'row_id': {'condition': '==', 'column': 'row_id'}, 'field': {'condition': '==', 'column': 'field'}}


model_router = SentoRouter(
                    schema=Schemaequipment_list_item,
                    db = get_db,
                    prefix="equipment",
                    db_model=Modelequipment_list_item,
                    create_schema = Schemaequipment_list_itemCreate,
                    update_schema = Schemaequipment_list_itemUpdate,
                    upsert_schema = Schemaequipment_list_itemUpsert,
                    get_all_filter_function= get_all_filter_function,
                    get_all_filter_meta = get_all_filter_meta,
                    create_one_callback=False,
                    update_one_callback=False,
                    delete_one_callback=False,
                    delete_all_callback=False,
                    unique_fields=['equipment_list_id', 'row_id', 'field']
                )