"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from typing import Optional
from utils.enums import *
from core.api.sento_router import SentoRouter
from core.database.db import get_db
from schemas.pid_file_link import pid_file_link as Schemapid_file_link
from schemas.pid_file_link import pid_file_linkCreate as Schemapid_file_linkCreate
from schemas.pid_file_link import pid_file_linkUpdate as Schemapid_file_linkUpdate
from schemas.pid_file_link import pid_file_linkUpsert as Schemapid_file_linkUpsert

from datetime import datetime

from models.pid_file_link import pid_file_link as Modelpid_file_link

def get_all_filter_function(pid_file_id:int=None,name:str=None,pid_file_page_id:int=None,type:str=None):
	return {"pid_file_id":pid_file_id,"name":name,"pid_file_page_id":pid_file_page_id,"type":type}


get_all_filter_meta = {'pid_file_id': {'condition': '==', 'column': 'pid_file_id'}, 'name': {'condition': '==', 'column': 'name'}, 'pid_file_page_id': {'condition': '==', 'column': 'pid_file_page_id'}, 'type': {'condition': '==', 'column': 'type'}}


model_router = SentoRouter(
                    schema=Schemapid_file_link,
                    db = get_db,
                    prefix="pid_file_link",
                    db_model=Modelpid_file_link,
                    create_schema = Schemapid_file_linkCreate,
                    update_schema = Schemapid_file_linkUpdate,
                    upsert_schema = Schemapid_file_linkUpsert,
                    get_all_filter_function= get_all_filter_function,
                    get_all_filter_meta = get_all_filter_meta,
                    create_one_callback=False,
                    update_one_callback=False,
                    delete_one_callback=False,
                    delete_all_callback=False,
                    unique_fields=['pid_file_id', 'name', 'pid_file_page_id', 'type']
                )