"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

"""start fresh

Revision ID: b8a43c1ff75e
Revises: 
Create Date: 2025-08-29 17:21:15.654518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8a43c1ff75e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('modified_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('equipment_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_equipment_list_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_list'))
    )
    op.create_index(op.f('ix_equipment_list_project_id'), 'equipment_list', ['project_id'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_job_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index(op.f('ix_job_project_id'), 'job', ['project_id'], unique=False)
    op.create_table('pid_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_uuid', sa.String(), nullable=True),
    sa.Column('technical_name', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_pid_file_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pid_file')),
    sa.UniqueConstraint('file_uuid', name='pid_file_uc', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_pid_file_project_id'), 'pid_file', ['project_id'], unique=False)
    op.create_table('equipment_list_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_list_id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_list_id'], ['equipment_list.id'], name=op.f('fk_equipment_list_item_equipment_list_id_equipment_list'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_list_item')),
    sa.UniqueConstraint('equipment_list_id', 'row_id', 'field', name='equipment_list_item_uc', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_equipment_list_item_equipment_list_id'), 'equipment_list_item', ['equipment_list_id'], unique=False)
    op.create_table('pid_file_page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid_file_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('rotation', sa.Integer(), nullable=True),
    sa.Column('image_s3_key', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pid_file_id'], ['pid_file.id'], name=op.f('fk_pid_file_page_pid_file_id_pid_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pid_file_page')),
    sa.UniqueConstraint('pid_file_id', 'page_number', name='pid_file_page_uc', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_pid_file_page_pid_file_id'), 'pid_file_page', ['pid_file_id'], unique=False)
    op.create_table('pid_file_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid_file_page_id', sa.Integer(), nullable=False),
    sa.Column('pid_file_id', sa.Integer(), nullable=False),
    sa.Column('linked_pid_file_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x0', sa.Integer(), nullable=False),
    sa.Column('y0', sa.Integer(), nullable=False),
    sa.Column('x1', sa.Integer(), nullable=False),
    sa.Column('y1', sa.Integer(), nullable=False),
    sa.Column('image_s3_key', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pid_file_id'], ['pid_file.id'], name=op.f('fk_pid_file_link_pid_file_id_pid_file'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pid_file_page_id'], ['pid_file_page.id'], name=op.f('fk_pid_file_link_pid_file_page_id_pid_file_page'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pid_file_link')),
    sa.UniqueConstraint('pid_file_id', 'name', 'pid_file_page_id', 'type', name='pid_file_link_uc', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_pid_file_link_pid_file_id'), 'pid_file_link', ['pid_file_id'], unique=False)
    op.create_index(op.f('ix_pid_file_link_pid_file_page_id'), 'pid_file_link', ['pid_file_page_id'], unique=False)
    op.create_table('pid_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid_file_page_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag_value', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('sub_type', sa.String(), nullable=False),
    sa.Column('x0', sa.Integer(), nullable=False),
    sa.Column('y0', sa.Integer(), nullable=False),
    sa.Column('x1', sa.Integer(), nullable=False),
    sa.Column('y1', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('candidates', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('modified_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pid_file_page_id'], ['pid_file_page.id'], name=op.f('fk_pid_tag_pid_file_page_id_pid_file_page'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pid_tag')),
    sa.UniqueConstraint('pid_file_page_id', 'name', 'type', name='pid_tag_uc', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_pid_tag_pid_file_page_id'), 'pid_tag', ['pid_file_page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pid_tag_pid_file_page_id'), table_name='pid_tag')
    op.drop_table('pid_tag')
    op.drop_index(op.f('ix_pid_file_link_pid_file_page_id'), table_name='pid_file_link')
    op.drop_index(op.f('ix_pid_file_link_pid_file_id'), table_name='pid_file_link')
    op.drop_table('pid_file_link')
    op.drop_index(op.f('ix_pid_file_page_pid_file_id'), table_name='pid_file_page')
    op.drop_table('pid_file_page')
    op.drop_index(op.f('ix_equipment_list_item_equipment_list_id'), table_name='equipment_list_item')
    op.drop_table('equipment_list_item')
    op.drop_index(op.f('ix_pid_file_project_id'), table_name='pid_file')
    op.drop_table('pid_file')
    op.drop_index(op.f('ix_job_project_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_equipment_list_project_id'), table_name='equipment_list')
    op.drop_table('equipment_list')
    op.drop_table('project')
    # ### end Alembic commands ###