"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

"""add column_id to equipment list item

Revision ID: f93c099c0be8
Revises: b8a43c1ff75e
Create Date: 2025-09-01 16:40:45.877793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93c099c0be8'
down_revision = 'b8a43c1ff75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_list_item', sa.Column('column_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('equipment_list_item_uc'), 'equipment_list_item', type_='unique')
    op.create_unique_constraint('equipment_list_item_uc', 'equipment_list_item', ['equipment_list_id', 'row_id', 'column_id', 'field'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('equipment_list_item_uc', 'equipment_list_item', type_='unique')
    op.create_unique_constraint(op.f('equipment_list_item_uc'), 'equipment_list_item', ['equipment_list_id', 'row_id', 'field'], postgresql_nulls_not_distinct=True)
    op.drop_column('equipment_list_item', 'column_id')
    # ### end Alembic commands ###