"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from datetime import datetime
from sqlalchemy.types import (
    Integer,
    BigInteger,
    String,
    DateTime,
    Float,
    Boolean,
    PickleType,
    Enum,
)
from sqlalchemy.schema import Column, UniqueConstraint, Index, ForeignKey
from sqlalchemy.sql import text, true, false
from sqlalchemy.sql.functions import func, Function
from sqlalchemy.orm import relationship, Mapped, mapped_column
from sqlalchemy.dialects.postgresql import JSONB, ARRAY

from utils.enums import *
from core.database.base_model import Base


class equipment_list_item(Base):
    __tablename__ = "equipment_list_item"

    id: Mapped[int] = mapped_column(
        Integer, nullable=False, primary_key=True, autoincrement=True
    )
    equipment_list_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("equipment_list.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    row_id: Mapped[int] = mapped_column(Integer, nullable=False)
    column_id: Mapped[int] = mapped_column(Integer, nullable=False)
    field: Mapped[str] = mapped_column(String, nullable=True)
    value: Mapped[str] = mapped_column(String, nullable=True)
    modified_on: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
    __table_args__ = (
        UniqueConstraint(
            "equipment_list_id",
            "row_id",
            "column_id",
            "field",
            name="equipment_list_item_uc",
            postgresql_nulls_not_distinct=True,
        ),
    )


# Probably want to implement a trigger dealing with this at the DB level instead.
# This will update even if values do not change
equipment_list_item._set_onupdate = {
    k: v.onupdate.arg
    for k, v in equipment_list_item.__table__.columns.items()
    if v.onupdate is not None and isinstance(v.onupdate.arg, Function)
}
