"""
DO NOT EDIT! THIS IS AN AUTOGENERATED FILE!!!!!
"""

from datetime import datetime
from sqlalchemy.types import (
    Integer,
    BigInteger,
    String,
    DateTime,
    Float,
    Boolean,
    PickleType,
    Enum,
)
from sqlalchemy.schema import Column, UniqueConstraint, Index, ForeignKey
from sqlalchemy.sql import text, true, false
from sqlalchemy.sql.functions import func, Function
from sqlalchemy.orm import relationship, Mapped, mapped_column
from sqlalchemy.dialects.postgresql import JSONB, ARRAY

from utils.enums import *
from core.database.base_model import Base


class pid_tag(Base):
    __tablename__ = "pid_tag"

    id: Mapped[int] = mapped_column(
        Integer, nullable=False, primary_key=True, autoincrement=True
    )
    pid_file_page_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("pid_file_page.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String, nullable=False)
    tag_value: Mapped[str] = mapped_column(String, nullable=False)
    type: Mapped[str] = mapped_column(String, nullable=False)
    sub_type: Mapped[str] = mapped_column(String, nullable=False)
    x0: Mapped[int] = mapped_column(Integer, nullable=False)
    y0: Mapped[int] = mapped_column(Integer, nullable=False)
    x1: Mapped[int] = mapped_column(Integer, nullable=False)
    y1: Mapped[int] = mapped_column(Integer, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    candidates: Mapped[dict | list] = mapped_column(
        JSONB(none_as_null=True), nullable=True
    )
    modified_on: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
    __table_args__ = (
        UniqueConstraint(
            "pid_file_page_id",
            "name",
            "type",
            name="pid_tag_uc",
            postgresql_nulls_not_distinct=True,
        ),
    )


# Probably want to implement a trigger dealing with this at the DB level instead.
# This will update even if values do not change
pid_tag._set_onupdate = {
    k: v.onupdate.arg
    for k, v in pid_tag.__table__.columns.items()
    if v.onupdate is not None and isinstance(v.onupdate.arg, Function)
}
